version: '3.9'

services:
  postgres:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./databases/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employee-platform